alias hello='echo Hola Germancin! have a great programming today!'
alias hi='echo Hola Germancin! have a great programming today!'
alias pp='python3 parallel.py'
alias check_workers='python3 check_workers.py'
alias check='python3 check_workers.py'
alias workers='python3 check_workers.py'